# Default configuration by Lazy Gentoo Install(2026)
# Github repo: https://github.com/Danilogames220/lazy-gentoo-install
# Pulled from the stage3 file: stage3-amd64-desktop-openrc-20260510T170106Z.tar.xz

# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.

# Compiler flags for all languages
COMMON_FLAGS="-march=native -O2 -pipe"

# Flags for C / C++
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"

# Flags for Rust
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

# If left undefined, Portage's default behavior is to:
# - set the MAKEOPTS jobs value to the same number of threads returned by `nproc`
# - set the MAKEOPTS load-average value slightly above the number of threads returned by `nproc`, due to it being a damped value
# Please replace '4' as appropriate for the system (min(RAM/2GB, threads), or leave it unset.
# * Search for MAKEOPTS in man 5 make.conf for more details.
MAKEOPTS="-j4 -l5"

# adding binary package hosts:
# https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Base#Optional:_Adding_a_binary_package_host

# configuring USE=
# https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Base#Optional:_Configuring_the_USE_variable
